-- Copyright (c) PRO-Robotech
-- SPDX-License-Identifier: BUSL-1.1

-- 0006: transactional-outbox для регистрации owner-tuple в FGA. Намерение
-- «register/unregister owner-tuple» пишется строкой в ТОЙ ЖЕ writer-TX, что
-- вставляет/удаляет ресурс (один commit, без dual-write). Отдельный
-- register-drainer (corelib outbox/drainer) применяет каждое намерение через
-- kacho-iam InternalIAMService.RegisterResource/Unregister.
--
-- ОТДЕЛЬНАЯ таблица — независимая от доменного `vpc_outbox` (Watch/realtime) —
-- изолирует FGA-relay drainer (применение RegisterResource, failure-mode'ы
-- «IAM недоступен»/poison) от доменного Watch-drainer. Ее форма точно совпадает
-- с claim/mark SQL corelib-drainer'а:
--   id (bigint PK), event_type, payload (jsonb), created_at, sent_at,
--   last_error, attempt_count
-- (drainer.claimRows: RETURNING id, event_type, payload, attempt_count;
--  markSuccess: SET sent_at=now(); markFailure/Poison: SET last_error, attempt_count).
--
-- Одна строка == один tuple (project-hierarchy и default-SG tuple — две строки):
-- drainer забирает/применяет строки независимо, поэтому poison/transient tuple
-- не блокирует остальные. LISTEN/NOTIFY-канал `kacho_vpc_fga_register_outbox`
-- (NEW.id) будит drainer на INSERT.
--
-- Within-service инвариант (DB-уровень): exactly-once claim обеспечивает
-- атомарный `UPDATE ... WHERE sent_at IS NULL AND attempt_count < $max ...
-- FOR UPDATE SKIP LOCKED RETURNING ...` corelib-drainer'а — без software TOCTOU.
-- Домен event_type гарантируется CHECK.

-- +goose Up
CREATE TABLE kacho_vpc.fga_register_outbox (
    id            bigint                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    text                     NOT NULL,
    payload       jsonb                    NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    sent_at       timestamp with time zone,
    last_error    text,
    attempt_count integer                  NOT NULL DEFAULT 0,
    CONSTRAINT fga_register_outbox_event_type_check
        CHECK (event_type IN ('fga.register', 'fga.unregister'))
);

-- Pending-rows partial index — the drainer claim scans (sent_at IS NULL).
CREATE INDEX fga_register_outbox_pending_idx
    ON kacho_vpc.fga_register_outbox (id)
    WHERE sent_at IS NULL;

-- LISTEN/NOTIFY wake-up: pg_notify on every INSERT (payload = NEW.id::text),
-- matching the corelib drainer Config.Channel = "kacho_vpc_fga_register_outbox".
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION kacho_vpc.fga_register_outbox_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM pg_notify('kacho_vpc_fga_register_outbox', NEW.id::text);
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER fga_register_outbox_notify_trg
    AFTER INSERT ON kacho_vpc.fga_register_outbox
    FOR EACH ROW EXECUTE FUNCTION kacho_vpc.fga_register_outbox_notify();

-- +goose Down
DROP TRIGGER IF EXISTS fga_register_outbox_notify_trg ON kacho_vpc.fga_register_outbox;
DROP FUNCTION IF EXISTS kacho_vpc.fga_register_outbox_notify();
DROP INDEX IF EXISTS kacho_vpc.fga_register_outbox_pending_idx;
DROP TABLE IF EXISTS kacho_vpc.fga_register_outbox;
